package org.git.common.constant;
public interface AppConstant {
	String APPLICATION_VERSION = "2.0.0";
	String BASE_PACKAGES = "org.git";
	String APPLICATION_NAME_PREFIX = "git-";
	String APPLICATION_AUTH_NAME = APPLICATION_NAME_PREFIX + "auth";
	String APPLICATION_LOGIN_INFO_NAME = APPLICATION_NAME_PREFIX + "login";
	String APPLICATION_DESK_NAME = APPLICATION_NAME_PREFIX + "desk";
	String APPLICATION_SYSTEM_NAME = APPLICATION_NAME_PREFIX + "system";
	String APPLICATION_USER_NAME = APPLICATION_NAME_PREFIX + "user";
	String APPLICATION_LOG_NAME = APPLICATION_NAME_PREFIX + "log";
	String APPLICATION_DEVELOP_NAME = APPLICATION_NAME_PREFIX + "develop";
	String APPLICATION_FLOWDESIGN_NAME = APPLICATION_NAME_PREFIX + "flowdesign";
	String APPLICATION_FLOW_NAME = APPLICATION_NAME_PREFIX + "flow";
	String APPLICATION_RESOURCE_NAME = APPLICATION_NAME_PREFIX + "resource";
	String APPLICATION_FRONT_NAME = APPLICATION_NAME_PREFIX + "front";
	String APPLICATION_TEST_NAME = APPLICATION_NAME_PREFIX + "test";
	String APPLICATION_DEMO_NAME = APPLICATION_NAME_PREFIX + "demo";
	String APPLICATION_BATCH_NAME = APPLICATION_NAME_PREFIX + "batch";
	String APPLICATION_CHART_NAME = APPLICATION_NAME_PREFIX + "chart";


	String DEV_CODE = "dev";
	String PROD_CODE = "prod";
	String TEST_CODE = "test";
	String OS_NAME_LINUX = "LINUX";
}
