ALTER TABLE
    "DB2INST1"."BLADE_DEPT" ALTER COLUMN "TENANT_ID" SET DEFAULT '000000';
ALTER TABLE
    "DB2INST1"."BLADE_DEPT" ALTER COLUMN "PARENT_ID" SET DEFAULT 0;
ALTER TABLE
    "DB2INST1"."BLADE_DEPT" ALTER COLUMN "IS_DELETED" SET DEFAULT 0
