CREATE TABLE "DB2INST1"."TB_FRONT_SERVICE_RECORD"  (
		  "ID" BIGINT NOT NULL ,
		  "GROUP_ID" BIGINT WITH DEFAULT NULL ,
		  "REQUESTOR_CODE" VARCHAR(10 OCTETS) NOT NULL ,
		  "RESPONDER_CODE" VARCHAR(10 OCTETS) NOT NULL ,
		  "REQUEST_MESSAGE" CLOB(1048576 OCTETS) LOGGED NOT COMPACT ,
		  "RESPONSE_MESSAGE" CLOB(1048576 OCTETS) LOGGED NOT COMPACT ,
		  "STATUS" INTEGER WITH DEFAULT NULL ,
		  "CREATE_TIME" DATE WITH DEFAULT NULL ,
		  "UPDATE_TIME" DATE WITH DEFAULT NULL ,
		  "TENANT_ID" VARCHAR(12 OCTETS) WITH DEFAULT NULL ,
		  "REMARK" VARCHAR(200 OCTETS) WITH DEFAULT NULL ,
		  "SERVICE_CODE" VARCHAR(50 OCTETS) WITH DEFAULT NULL ,
		  "SERVICE_SN" VARCHAR(50 OCTETS) WITH DEFAULT NULL ,
		  "SERVICE_TIME" DATE WITH DEFAULT NULL ,
		  "BIZ_SN" VARCHAR(50 OCTETS) WITH DEFAULT NULL ,
		  "RETRY_COUNT" INTEGER WITH DEFAULT NULL )
		 IN "USERSPACE1"
		 ORGANIZE BY ROW  ;
COMMENT ON TABLE "DB2INST1"."TB_FRONT_SERVICE_RECORD" IS '前置服务记录表' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."BIZ_SN" IS '业务流水号' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."CREATE_TIME" IS '创建时间' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."GROUP_ID" IS '分组ID' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."ID" IS '记录ID' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."REMARK" IS '备注' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."REQUESTOR_CODE" IS '请求终端' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."REQUEST_MESSAGE" IS '请求报文' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."RESPONDER_CODE" IS '响应终端' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."RESPONSE_MESSAGE" IS '响应报文' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."RETRY_COUNT" IS '重试次数' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."SERVICE_CODE" IS '服务代码' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."SERVICE_SN" IS '交易流水号' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."SERVICE_TIME" IS '交易时间' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."STATUS" IS '处理状态' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."TENANT_ID" IS '租户ID' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_SERVICE_RECORD"."UPDATE_TIME" IS '修改时间' ;
ALTER TABLE "DB2INST1"."TB_FRONT_SERVICE_RECORD"
	ADD CONSTRAINT "TB_FRONT_SERVICE_RECORD_PK" PRIMARY KEY
		("ID") ;
GRANT CONTROL ON TABLE "DB2INST1"."TB_FRONT_SERVICE_RECORD" TO USER "DB2INST1"  ;
