
drop table TB_FRONT_TERMINAL_CONFIG;
CREATE TABLE "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"  (
		  "ID" BIGINT NOT NULL ,
		  "TERMINAL_CODE" VARCHAR(20 OCTETS) ,
		  "TERMINAL_NAME" VARCHAR(100 OCTETS) ,
		  "TERMINAL_SHORT_NAME" VARCHAR(50 OCTETS) ,
		  "TERMINAL_ROLE" VARCHAR(10 OCTETS) ,
		  "SEND_ADDRESS" VARCHAR(100 OCTETS) ,
		  "RECEIVE_ADDRESS" VARCHAR(100 OCTETS),
		  "CONNECT_MODE" VARCHAR(10 OCTETS) ,
		  "STATUS" BIGINT NOT NULL ,
		  "IS_AUTH" BIGINT ,
		  "TOKEN" VARCHAR(200 OCTETS) ,
		  "REMARK" VARCHAR(200 OCTETS) ,
		  "PARENT_TERMINAL_ID" BIGINT ,
		  "CREATE_DEPT" BIGINT ,
		  "CREATE_USER" BIGINT ,
		  "CREATE_TIME" DATE ,
		  "UPDATE_USER" BIGINT ,
		  "UPDATE_TIME" DATE ,
		  "TENANT_ID" VARCHAR(12 OCTETS) ,
		  "IS_DELETED" BIGINT )
		 IN "USERSPACE1"
		 ORGANIZE BY ROW  ;

COMMENT ON TABLE "DB2INST1"."TB_FRONT_TERMINAL_CONFIG" IS '前置终端配置表' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."CONNECT_MODE" IS '连接方式' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."CREATE_DEPT" IS '创建机构' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."CREATE_TIME" IS '创建时间' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."CREATE_USER" IS '创建人' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."ID" IS '主键' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."IS_AUTH" IS '是否授权' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."IS_DELETED" IS '是否已删除' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."PARENT_TERMINAL_ID" IS '父级终端' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."SEND_ADDRESS" IS '发送地址' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."RECEIVE_ADDRESS" IS '接收地址' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."REMARK" IS '备注' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."STATUS" IS '是否启用' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."TENANT_ID" IS '租户ID' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."TERMINAL_CODE" IS '终端代码' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."TERMINAL_NAME" IS '终端名称' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."TERMINAL_SHORT_NAME" IS '终端缩写' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."TOKEN" IS '校验码' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."UPDATE_TIME" IS '修改时间' ;
COMMENT ON COLUMN "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"."UPDATE_USER" IS '修改人' ;
ALTER TABLE "DB2INST1"."TB_FRONT_TERMINAL_CONFIG"
	ADD CONSTRAINT "TB_FRONT_TERMINAL_CONFIG_PK" PRIMARY KEY ("ID") ;
GRANT CONTROL ON TABLE "DB2INST1"."TB_FRONT_TERMINAL_CONFIG" TO USER "DB2INST1"  ;
