CREATE TABLE TB_LOGIN_LOG (ID VARCHAR(32) NOT NULL, ACCOUNT VARCHAR(32) NOT NULL, USER_NAME VARCHAR(50) NOT NULL, ORG_NAME VARCHAR(100), ACTION_DATETIME VARCHAR(20) NOT NULL, ACTION_CLIENT_IP VARCHAR(30), ACTION_TYPE VARCHAR(1) NOT NULL, PRIMARY KEY (ID));
COMMENT ON TABLE TB_LOGIN_LOG IS '用户登录退出记录表';
COMMENT ON COLUMN TB_LOGIN_LOG.ID IS '主键';
COMMENT ON COLUMN TB_LOGIN_LOG.ACCOUNT IS '登录帐号';
COMMENT ON COLUMN TB_LOGIN_LOG.USER_NAME IS '用户名称';
COMMENT ON COLUMN TB_LOGIN_LOG.ORG_NAME IS '登录机构';
COMMENT ON COLUMN TB_LOGIN_LOG.ACTION_DATETIME IS '操作时间';
COMMENT ON COLUMN TB_LOGIN_LOG.ACTION_CLIENT_IP IS '操作者IP';
COMMENT ON COLUMN TB_LOGIN_LOG.ACTION_TYPE IS '操作类型(1 登录 2 正常退出 3 强制退出)';
