--额度表
drop table TB_PAR_CRD;
create table TB_PAR_CRD (
    crd_product_num    VARCHAR(36) NOT NULL,
    CRD_PRODUCT_NAME    VARCHAR(50),
    SUPER_CRD_Num     VARCHAR(50),
    SUPER_CRD_NAME  VARCHAR(50),
    CRD_LOWER_LIMIT   VARCHAR(50),
    CRD_UPPER_LIMIT   VARCHAR(50),
    OPEN_LOWER_LIMIT   VARCHAR(50),
    OPEN_UPPER_LIMIT   VARCHAR(50),
    CURRENCY_CD   VARCHAR(10),
    CRD_SYS_STATUS    VARCHAR(1),
    crd_DESCR        VARCHAR(300),
    crd_level        VARCHAR(4),
    user_num  VARCHAR(20),
    org_num   VARCHAR(20),
    update_user_num  VARCHAR(20),
    update_org_num   VARCHAR(20),
    CREATE_TIME DATE,
    UPDATE_TIME DATE ,
    is_deleted BIGINT NULL DEFAULT 0 ,
    RESERVED_FIELD1      VARCHAR(30),
    RESERVED_FIELD2      VARCHAR(30) ,
    RESERVED_FIELD3      VARCHAR(30),
    RESERVED_FIELD4      VARCHAR(30),
    RESERVED_FIELD5      VARCHAR(30),
    constraint P_Key_1 primary key (crd_product_num)
);
COMMENT ON TABLE TB_PAR_CRD IS '额度表';
COMMENT ON COLUMN TB_PAR_CRD.crd_product_num IS '额度品种编号';
COMMENT ON COLUMN TB_PAR_CRD.CRD_PRODUCT_NAME IS '额度体系名称';
COMMENT ON COLUMN TB_PAR_CRD.SUPER_CRD_Num IS '额度父类编号';
COMMENT ON COLUMN TB_PAR_CRD.SUPER_CRD_NAME IS '额度父类名称';
COMMENT ON COLUMN TB_PAR_CRD.CRD_LOWER_LIMIT IS '额度下限';
COMMENT ON COLUMN TB_PAR_CRD.CRD_UPPER_LIMIT IS '额度上限';
COMMENT ON COLUMN TB_PAR_CRD.OPEN_LOWER_LIMIT IS '敞口下限';
COMMENT ON COLUMN TB_PAR_CRD.OPEN_UPPER_LIMIT IS '敞口上限';
COMMENT ON COLUMN TB_PAR_CRD.CURRENCY_CD IS '币种';
COMMENT ON COLUMN TB_PAR_CRD.CRD_SYS_STATUS IS '产品状态，1：有效 2：无效';
COMMENT ON COLUMN TB_PAR_CRD.crd_DESCR IS '额度产品描述';
COMMENT ON COLUMN TB_PAR_CRD.crd_level IS '额度产品级别';
COMMENT ON COLUMN TB_PAR_CRD.user_num IS '经办人编号';
COMMENT ON COLUMN TB_PAR_CRD.org_num IS '经办机构编号';
COMMENT ON COLUMN TB_PAR_CRD.update_user_num IS '修改人编号';
COMMENT ON COLUMN TB_PAR_CRD.update_org_num IS '修改人机构编号';
COMMENT ON COLUMN TB_PAR_CRD.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TB_PAR_CRD.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN TB_PAR_CRD.is_deleted IS '是否已删除';
COMMENT ON COLUMN TB_PAR_CRD.RESERVED_FIELD1 IS '预留字段1';
COMMENT ON COLUMN TB_PAR_CRD.RESERVED_FIELD2 IS '预留字段2';
COMMENT ON COLUMN TB_PAR_CRD.RESERVED_FIELD3 IS '预留字段3';
COMMENT ON COLUMN TB_PAR_CRD.RESERVED_FIELD4 IS '预留字段4';
COMMENT ON COLUMN TB_PAR_CRD.RESERVED_FIELD5 IS '预留字段5';
